# Generated by Django 4.1 on 2022-08-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("naac", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ssr_text_converter",
            name="progress_bar",
        ),
    ]
