# Generated by Django 4.1 on 2022-08-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("naac", "0002_ssr_text_converter_ssr_geo_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ssr_text_converter",
            name="pdf",
        ),
    ]
