# Generated by Django 4.1 on 2022-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naac", "0004_ssr_text_converter_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssr_geo_tag",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
