# Generated by Django 4.1 on 2022-08-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naac", "0005_ssr_geo_tag_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssr_text_converter",
            name="status",
            field=models.CharField(default="None", max_length=100, null=True),
        ),
    ]
