# Generated by Django 4.1 on 2022-08-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naac", "0006_ssr_text_converter_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssr_geo_tag",
            name="lat_convert",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ssr_geo_tag",
            name="latitude",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ssr_geo_tag",
            name="long_convert",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ssr_geo_tag",
            name="longitude",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ssr_geo_tag",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
