# Generated by Django 4.1 on 2022-08-24 09:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("naac", "0008_iiqa_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iiqa",
            name="phn_no_clg",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="iiqa",
            name="phn_no_principal",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="iiqa",
            name="phn_no_principal_alt",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
